function p = pathdef
%PATHDEF Search path defaults.
%   PATHDEF returns a string that can be used as input to MATLABPATH
%   in order to set the path.

  
%   Copyright 1984-2000 The MathWorks, Inc.
%   $Revision: 1.4 $ $Date: 2000/06/01 16:19:21 $

% PATH DEFINED HERE -- Don't change this line.

p = [...
matlabroot,'\myfun;',...
matlabroot,'\work;',...
matlabroot,'\PROPACK;',...
matlabroot,'\toolbox\matlab\general;',...
matlabroot,'\toolbox\matlab\graph2d;',...
matlabroot,'\toolbox\matlab\graph3d;',...
matlabroot,'\toolbox\matlab\graphics;',...
matlabroot,'\toolbox\matlab\lang;',...
matlabroot,'\toolbox\local;',...
matlabroot,'\toolbox\signal;',...
matlabroot,'\toolbox\matlab\datatypes;',...
matlabroot,'\toolbox\matlab\ops;',...
matlabroot,'\toolbox\matlab\elfun;',...
matlabroot,'\toolbox\matlab\strfun;',...
matlabroot,'\toolbox\matlab\datafun;',...
matlabroot,'\toolbox\matlab\uitools;',...

     ...
];






p = [userpath,p];
